"""initial schema

Revision ID: 7e9f9b0f9fc6
Revises: 
Create Date: 2026-06-04 19:34:57.765726
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e9f9b0f9fc6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ativos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=120), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('setor', sa.String(length=80), nullable=True),
    sa.Column('subsetor', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ativos_ticker'), ['ticker'], unique=True)

    op.create_table('cotacoes_historicas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('preco_fechamento', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cotacoes_historicas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cotacoes_historicas_ativo_id'), ['ativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cotacoes_historicas_data'), ['data'], unique=False)

    op.create_table('indicadores_fundamentalistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('vpa', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('lpa', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('p_l', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('roe', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(precision=18, scale=4), nullable=True),
    sa.Column('ultima_atualizacao', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('indicadores_fundamentalistas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_indicadores_fundamentalistas_ativo_id'), ['ativo_id'], unique=False)

    op.create_table('proventos_recebidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('data_com', sa.Date(), nullable=True),
    sa.Column('tipo_provento', sa.String(length=20), nullable=False),
    sa.Column('valor_liquido', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proventos_recebidos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proventos_recebidos_ativo_id'), ['ativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proventos_recebidos_data_com'), ['data_com'], unique=False)
        batch_op.create_index(batch_op.f('ix_proventos_recebidos_data_pagamento'), ['data_pagamento'], unique=False)

    op.create_table('transacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ativo_id', sa.Integer(), nullable=False),
    sa.Column('tipo_operacao', sa.String(length=10), nullable=False),
    sa.Column('data_operacao', sa.Date(), nullable=False),
    sa.Column('quantidade', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('taxas_corretagem', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['ativo_id'], ['ativos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transacoes_ativo_id'), ['ativo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transacoes_data_operacao'), ['data_operacao'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transacoes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transacoes_data_operacao'))
        batch_op.drop_index(batch_op.f('ix_transacoes_ativo_id'))

    op.drop_table('transacoes')
    with op.batch_alter_table('proventos_recebidos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proventos_recebidos_data_pagamento'))
        batch_op.drop_index(batch_op.f('ix_proventos_recebidos_data_com'))
        batch_op.drop_index(batch_op.f('ix_proventos_recebidos_ativo_id'))

    op.drop_table('proventos_recebidos')
    with op.batch_alter_table('indicadores_fundamentalistas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_indicadores_fundamentalistas_ativo_id'))

    op.drop_table('indicadores_fundamentalistas')
    with op.batch_alter_table('cotacoes_historicas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cotacoes_historicas_data'))
        batch_op.drop_index(batch_op.f('ix_cotacoes_historicas_ativo_id'))

    op.drop_table('cotacoes_historicas')
    with op.batch_alter_table('ativos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ativos_ticker'))

    op.drop_table('ativos')
    # ### end Alembic commands ###
